kind: Deployment
apiVersion: apps/v1
metadata:
  name: gemini-deployment
  namespace: gemini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      nodeSelector:
        nodegroup: app
      containers:
      - name: gemini-clone
        image: mrsinghdocker/gemini-clone:10
        ports:
        - containerPort: 3000
        env:
        - name: GOOGLE_ID
          valueFrom:
            configMapKeyRef:
              name: gemini-configmap
              key: GOOGLE_ID
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: GOOGLE_SECRET
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: gemini-configmap
              key: MONGODB_URI
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: gemini-configmap
              key: NEXTAUTH_URL
        - name: NEXT_PUBLIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: NEXT_PUBLIC_API_KEY
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"