kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gemini-ingress
  namespace: gemini
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - gemini.mrsinghincloud.com
    secretName: gemini-tls-secret
  ingressClassName: nginx
  rules:
  - host: gemini.mrsinghincloud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gemini-svc
            port:
              number: 80
