kind: Secret
apiVersion: v1
metadata:
  name: gemini-secrets
  namespace: gemini
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLVJDcG1zclNoSnpkSWVScFlhRDNKNURQZG8xa24= # Base64 for google key
  NEXTAUTH_SECRET: VSt3dDg5VGdHWmlWUi9YeTluN0RPWWpDeFJYQ0N3Q0JEeUpiSVJDa3Q1dz0= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5QmpiNmFRaURwNm9sVEpva2F6Nm9JaFpJMXY3Ukpvcksw # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: cm9vdEBhZG1pbg==  # Base64 for root@admin