server:
  service:
    type: LoadBalancer
  persistentVolume:
    enabled: true
    storageClass: "gp3" 
    size: 8Gi
  nodeSelector:
    nodegroup: system
  tolerations:
  - key: nodegroup
    value: system
    operator: Equal
    effect: NoSchedule

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "gp3" 
    size: 2Gi
  nodeSelector:
    nodegroup: system
  tolerations:
    - key: nodegroup
      operator: Equal
      value: system
      effect: NoSchedule

pushgateway:
  nodeSelector:
    nodegroup: system
  tolerations:
    - key: nodegroup
      operator: Equal
      value: system
      effect: NoSchedule