server:
  nodeSelector:
    nodegroup: system
  tolerations:
  - key: nodegroup
    value: system
    operator: Equal
    effect: NO_SCHEDULE

alertmanager:
  nodeSelector:
    nodegroup: system
  tolerations:
    - key: nodegroup
      operator: Equal
      value: system
      effect: NoSchedule

pushgateway:
  nodeSelector:
    nodegroup: system
  tolerations:
    - key: nodegroup
      operator: Equal
      value: system
      effect: NoSchedule